/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TrafficStorage } from "./TrafficStorage";
export * as factories from "./factories";
export { TrafficStorage__factory } from "./factories/TrafficStorage__factory";
